#!/bin/bash
#SBATCH -J Jianyuan
#SBATCH -o out/my_output
#SBATCH --mem=32GB
#SBATCH -t 5-00:00:00
#SBATCH -n 1
#SBATCH -c 4
#SBATCH -p gpu
#SBATCH --gres=gpu:1


module load anaconda
module load cuda
source activate research
python mosi_train.py
